#include <entity/implemented/MAIN_TEST_SUITE__ANCIENTSGAME_ENTITY_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_ENTITY_IMPLEMENTED, 4,
INCLUDE_SUITE(ag__entity_player),
INCLUDE_SUITE(ag__entity_skeleton),
INCLUDE_SUITE(entity_registrar),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_ENTITY_IMPLEMENTED, END_TESTS);

