#include <entity/MAIN_TEST_SUITE__ANCIENTSGAME_ENTITY.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_ENTITY, 5,
INCLUDE_SUITE(reserves),
INCLUDE_SUITE(f_entity_initializer),
INCLUDE_SUITE(ANCIENTSGAME_ENTITY_IMPLEMENTED),
INCLUDE_SUITE(ANCIENTSGAME_ENTITY_HANDLERS),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_ENTITY, END_TESTS);

