#include <game_action/MAIN_TEST_SUITE__ANCIENTSGAME_GAME_ACTION.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_GAME_ACTION, 2,
INCLUDE_SUITE(ANCIENTSGAME_GAME_ACTION_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_GAME_ACTION, END_TESTS);

