#include <inventory/MAIN_TEST_SUITE__ANCIENTSGAME_INVENTORY.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_INVENTORY, 2,
INCLUDE_SUITE(ANCIENTSGAME_INVENTORY_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_INVENTORY, END_TESTS);

