#include <ui/MAIN_TEST_SUITE__ANCIENTSGAME_UI.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_UI, 7,
INCLUDE_SUITE(ui_ag__button),
INCLUDE_SUITE(ag_fonts),
INCLUDE_SUITE(ui_ag__slider),
INCLUDE_SUITE(ui_ag__text_box),
INCLUDE_SUITE(ui_ag__text),
INCLUDE_SUITE(ANCIENTSGAME_UI_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_UI, END_TESTS);

