#include <rendering/MAIN_TEST_SUITE__ANCIENTSGAME_RENDERING.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_RENDERING, 4,
INCLUDE_SUITE(ag__graphics_window),
INCLUDE_SUITE(ANCIENTSGAME_RENDERING_IMPLEMENTED),
INCLUDE_SUITE(ANCIENTSGAME_RENDERING_HANDLERS),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_RENDERING, END_TESTS);

