#include <world/MAIN_TEST_SUITE__ANCIENTSGAME_WORLD.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_WORLD, 5,
INCLUDE_SUITE(ag__world),
INCLUDE_SUITE(ag__tile_logic_record),
INCLUDE_SUITE(ag__tile),
INCLUDE_SUITE(ANCIENTSGAME_WORLD_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_WORLD, END_TESTS);

