#include <scene/MAIN_TEST_SUITE__ANCIENTSGAME_SCENE.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_SCENE, 2,
INCLUDE_SUITE(ANCIENTSGAME_SCENE_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_SCENE, END_TESTS);

