#include <rendering/implemented/MAIN_TEST_SUITE__ANCIENTSGAME_RENDERING_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_RENDERING_IMPLEMENTED, 4,
INCLUDE_SUITE(aliased_texture_registrar),
INCLUDE_SUITE(sprite_animation_registrar),
INCLUDE_SUITE(ag__sprite_humanoid),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_RENDERING_IMPLEMENTED, END_TESTS);

