#include </home/shalidor/Projects/Projects__Lavender/AncientsGame/tests/core/include/MAIN_TEST_SUITE___.h>

INCLUDE_SUB_SUITES(_, 19,
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),
INCLUDE_SUITE(_),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(_, END_TESTS);

