#include <MAIN_TEST_SUITE__ANCIENTSGAME_ANCIENTS_GAME.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_ANCIENTS_GAME, 9,
INCLUDE_SUITE(ag__client),
INCLUDE_SUITE(ANCIENTSGAME_RENDERING),
INCLUDE_SUITE(ANCIENTSGAME_WORLD),
INCLUDE_SUITE(ANCIENTSGAME_INVENTORY),
INCLUDE_SUITE(ANCIENTSGAME_GAME_ACTION),
INCLUDE_SUITE(ANCIENTSGAME_ENTITY),
INCLUDE_SUITE(ANCIENTSGAME_UI),
INCLUDE_SUITE(ANCIENTSGAME_SCENE),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_ANCIENTS_GAME, END_TESTS);

