#ifndef AG__DEFINES_H
#define AG__DEFINES_H

#include "defines.h"
#include "ag__defines_weak.h"

#define SPRITE_FRAME_WIDTH__ENTITY_HUMANOID_ARMORED 16
#define SPRITE_FRAME_HEIGHT__ENTITY_HUMANOID_ARMORED 16

#define SPRITE_FRAME_WIDTH__ENTITY_HUMANOID_UNARMORED 6
#define SPRITE_FRAME_HEIGHT__ENTITY_HUMANOID_UNARMORED 4

#define SPRITE_FRAME_COL__ENTITY_HUMANOID__IDLE 0
#define SPRITE_FRAME_COL__ENTITY_HUMANOID__WALK 1
#define SPRITE_FRAME_COL__ENTITY_HUMANOID__USE 3
#define SPRITE_FRAME_COL__ENTITY_HUMANOID__HURT 0
#define SPRITE_FRAME_COL__ENTITY_HUMANOID__DIE 1
#define SPRITE_FRAME_COL__ENTITY_HUMANOID__SLEEP 3

#define SPRITE_ANIMATION_FRAME_COUNT__ENTITY_HUMANOID__IDLE 0
#define SPRITE_ANIMATION_FRAME_COUNT__ENTITY_HUMANOID__WALK 2
#define SPRITE_ANIMATION_FRAME_COUNT__ENTITY_HUMANOID__USE 2
#define SPRITE_ANIMATION_FRAME_COUNT__ENTITY_HUMANOID__HURT 1
#define SPRITE_ANIMATION_FRAME_COUNT__ENTITY_HUMANOID__DIE 2
#define SPRITE_ANIMATION_FRAME_COUNT__ENTITY_HUMANOID__SLEEP 0

#define SPRITE_FRAME_ROW__ENTITY_HUMANOID__SIDE_FACING 0
#define SPRITE_FRAME_ROW__ENTITY_HUMANOID__FORWARD_FACING 1
#define SPRITE_FRAME_ROW__ENTITY_HUMANOID__BACK_FACING 2
#define SPRITE_FRAME_ROW__ENTITY_HUMANOID__FALLING 3

#define SPRITE_FRAME_COL_GROUP_OFFSET__ENTITY_HUMANOID 6
#define SPRITE_FRAME_ROW_GROUP_OFFSET__ENTITY_HUMANOID (3*16)

#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_CLOTH 1
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_IRON 2
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_IRON__RUSTED 3
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_STEEL 4
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_STEEL__DIAMOND 5
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_STEEL__AMETHYST 6
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_GOLD 7
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_GOLD__DIAMOND 8
#define SPRITE_FRAME_GROUP_INDEX__ENTITY_HUMANOID__ARMOR_GOLD__AMETHYST 9

#define ENTITY_FLAG__IS_UNDEAD ENTITY_FLAG__CUSTOM_0

#define EQUIPMENT_ITEM_STACK_QUANTITY_OF 6

typedef union Equipment_t {
    struct {
        Item_Stack item_stacks[
            EQUIPMENT_ITEM_STACK_QUANTITY_OF];
    };
    struct {
        Item_Stack item_stacks__equipment[
            EQUIPMENT_ITEM_STACK_QUANTITY_OF
                - INVENTORY_CONSUMABLES_QUANTITY_OF];
        Item_Stack item_stack__consumables[
            INVENTORY_CONSUMABLES_QUANTITY_OF];
    };
    struct {
        Item_Stack item_stack__armor;
        Item_Stack item_stack__main_hand;
        Item_Stack item_stack__off_hand;

        Item_Stack item_stack__consumable_1;
        Item_Stack item_stack__consumable_2;
        Item_Stack item_stack__consumable_3;
    };
} Equipment;

#endif
