#include "world/implemented/tile_logic_table_registrar.h"
#include "types/implemented/tile_cover_kind.h"
#include "world/ag__tile_logic_record.h"
#include "defines.h"
#include "defines_weak.h"

static inline
void register_tile_logic_table_entry_for__tile_kind(
        Tile_Logic_Table *p_tile_logic_table,
        Tile_Kind the_kind_of__tile,
        Tile_Logic_Flags__u16 tile_logic_flags,
        i32F4 tile_height) {
    p_tile_logic_table->tile_logic_table_data.tile_logic_record__tile_kind[
        the_kind_of__tile].tile_logic_flags__u8 = tile_logic_flags;
    p_tile_logic_table->tile_logic_table_data.tile_logic_record__tile_kind[
        the_kind_of__tile].tile_height__i32F4 = tile_height;
}

static inline
void register_tile_logic_table_entry_for__tile_cover_kind(
        Tile_Logic_Table *p_tile_logic_table,
        Tile_Cover_Kind the_kind_of__tile_cover,
        Tile_Logic_Flags__u16 tile_logic_flags,
        i32F4 tile_height) {
    p_tile_logic_table->tile_logic_table_data.tile_logic_record__tile_cover_kind[
        the_kind_of__tile_cover].tile_logic_flags__u8 = tile_logic_flags;
    p_tile_logic_table->tile_logic_table_data.tile_logic_record__tile_cover_kind[
        the_kind_of__tile_cover].tile_height__i32F4 = tile_height;
}

void register_tile_logic_tables(
        Game *p_game,
        Tile_Logic_Table *p_tile_logic_table) {
    p_tile_logic_table->m_get_tile_logic_record =
        m_tile_logic_table__get_tile_logic_record__ag;
    register_tile_logic_table_entry_for__tile_kind(
            p_tile_logic_table, 
            Tile_Kind__None, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND,
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__None, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND,
            0);

    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Amethyst__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);



    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Diamond__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);



    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Gold__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Stone_Brick__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Dirt__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Grass__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Iron__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    



    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Sand__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);





    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Leaves__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Snow__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Steel__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__Concave_Corner__North_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__Concave_Corner__South_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__Convex_Corner__North_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__Convex_Corner__South_East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__North__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__North__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__South__East, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__South__East_West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__West, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__West__North, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Stair__Wood__West__North_South, 
            TILE_LOGIC_FLAG__IS_WITHOUT_GROUND, 
            TILE_STAIR_HEIGHT);




    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Amethyst, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Diamond, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Dirt, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Gold, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Grass, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Iron, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Sand, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Sandstone, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Steel, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Stone, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Stone_Brick, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
    register_tile_logic_table_entry_for__tile_cover_kind(
            p_tile_logic_table, 
            Tile_Cover_Kind__Wall__Wood, 
            TILE_LOGIC_FLAG__IS_UNPASSABLE, 
            0);
}
