#include <rendering/handlers/MAIN_TEST_SUITE__ANCIENTSGAME_RENDERING_HANDLERS.h>

INCLUDE_SUB_SUITES(ANCIENTSGAME_RENDERING_HANDLERS, 2,
INCLUDE_SUITE(ag__sprite_animation_handler),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ANCIENTSGAME_RENDERING_HANDLERS, END_TESTS);

